name: fastotv_dart
author: Alexandr Topilski <support@fastogt.com>
description: FastoTV Dart client.
version: 1.2.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  crypto:
  archive:
  xml: '>=3.0.0'
  quiver: '>=2.0.0 <3.0.0'
  intl: ^0.16.1
